CAP_FREQ_HEADER =('**********************************'
                  '\nMeasurement Type:\t{}'
                  '\nMeasurement Date:\t{}'
                  '\nMeasurement Time:\t{}'
                  '\n******Measurement Parameters******'
                  '\nMeasurement Number:\t{}'
                  '\nStart Frequency [Hz]:\t{}'
                  '\nStop Frequency [Hz]:\t{}'
                  '\nOscillator [{}]:\t{}'
                  '\nDC Bias [{}]:\t{}'
                  '\nStep Delay (ms):\t{}'
                  '\n***********Sample Notes***********'
                  '\n{}'
                  '\n************End Header************\n\n')
