CAP_FREQ_HEADER = ('**********************************'
                   '\nMeasurement Type:\t{meas_type}'
                   '\nMeasurement Date:\t{meas_date}'
                   '\nMeasurement Time:\t{meas_time}'
                   '\n******Measurement Parameters******'
                   '\nMeasurement Number:\t{meas_num}'
                   '\nStart Frequency [Hz]:\t{start_freq}'
                   '\nStop Frequency [Hz]:\t{stop_freq}'
                   '\nOscillator [{osc_type}]:\t{osc}'
                   '\nDC Bias [{bias_type}]:\t{bias}'
                   '\nPre Measurement Delay (ms):\t{pre_meas_delay}'
                   '\n***********Sample Notes***********'
                   '\n{notes}'
                   '\n************End Header************\n\n')

CAP_FREQ_TEMP_HEADER = ('**********************************'
                        '\nMeasurement Type:\t{meas_type}'
                        '\nMeasurement Date:\t{meas_date}'
                        '\nMeasurement Time:\t{meas_time}'
                        '\n******Measurement Parameters******'
                        '\nMeasurement Number:\t{meas_num}'
                        '\nStart Frequency [Hz]:\t{start_freq}'
                        '\nStop Frequency [Hz]:\t{stop_freq}'
                        '\nOscillator [{osc_type}]:\t{osc}'
                        '\nDC Bias [{bias_type}]:\t{bias}'
                        '\nPre Measurement Delay (ms):\t{pre_meas_delay}'
                        '\n*************Thermal*************'
                        '\nRamp Rate:\t{ramp}'
                        '\nDwell Before Measurement:\t{dwell}'
                        '\nStabilization Measurement Interval:\t{stab_int}'
                        '\nUser Probe Average T [°C]:\t{user_avg}'
                        '\nUser Probe Std. Deviation [°C]:\t{user_stdev}'
                        '\nChamber Probe Average T [°C]:\t{chamber_avg}'
                        '\nChamber Probe Std. Deviation [°C]:\t{chamber_stdev}'
                        '\nImpedance Value Standard Deviation [Ohm]:\t{z_stdev}'
                        '\n***********Sample Notes***********'
                        '\n{notes}'
                        '\n************End Header************\n\n')
