# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/ui/cap_freq_temp_tabs.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_cap_freq(object):
    def setupUi(self, cap_freq):
        cap_freq.setObjectName("cap_freq")
        cap_freq.resize(1486, 967)
        cap_freq.setTabPosition(QtWidgets.QTabWidget.West)
        self.tab_meas_setup = QtWidgets.QWidget()
        self.tab_meas_setup.setObjectName("tab_meas_setup")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_meas_setup)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gbox_meas_set_params = QtWidgets.QGroupBox(self.tab_meas_setup)
        self.gbox_meas_set_params.setObjectName("gbox_meas_set_params")
        self.formLayout_2 = QtWidgets.QFormLayout(self.gbox_meas_set_params)
        self.formLayout_2.setObjectName("formLayout_2")
        self.lbl_function = QtWidgets.QLabel(self.gbox_meas_set_params)
        self.lbl_function.setObjectName("lbl_function")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_function)
        self.combo_function = QtWidgets.QComboBox(self.gbox_meas_set_params)
        self.combo_function.setObjectName("combo_function")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_function)
        self.lbl_meas_time = QtWidgets.QLabel(self.gbox_meas_set_params)
        self.lbl_meas_time.setObjectName("lbl_meas_time")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_meas_time)
        self.combo_meas_time = QtWidgets.QComboBox(self.gbox_meas_set_params)
        self.combo_meas_time.setObjectName("combo_meas_time")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.combo_meas_time)
        self.lbl_data_averaging = QtWidgets.QLabel(self.gbox_meas_set_params)
        self.lbl_data_averaging.setObjectName("lbl_data_averaging")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_data_averaging)
        self.ln_data_averaging = QtWidgets.QLineEdit(self.gbox_meas_set_params)
        self.ln_data_averaging.setObjectName("ln_data_averaging")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ln_data_averaging)
        self.lbl_num_pts = QtWidgets.QLabel(self.gbox_meas_set_params)
        self.lbl_num_pts.setObjectName("lbl_num_pts")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_num_pts)
        self.ln_num_pts = QtWidgets.QLineEdit(self.gbox_meas_set_params)
        self.ln_num_pts.setObjectName("ln_num_pts")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ln_num_pts)
        self.lbl_pre_meas_delay = QtWidgets.QLabel(self.gbox_meas_set_params)
        self.lbl_pre_meas_delay.setObjectName("lbl_pre_meas_delay")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_pre_meas_delay)
        self.ln_pre_meas_delay = QtWidgets.QLineEdit(self.gbox_meas_set_params)
        self.ln_pre_meas_delay.setObjectName("ln_pre_meas_delay")
        self.formLayout_2.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ln_pre_meas_delay)
        self.lbl_range = QtWidgets.QLabel(self.gbox_meas_set_params)
        self.lbl_range.setObjectName("lbl_range")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_range)
        self.combo_range = QtWidgets.QComboBox(self.gbox_meas_set_params)
        self.combo_range.setObjectName("combo_range")
        self.formLayout_2.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.combo_range)
        self.lbl_signal_type = QtWidgets.QLabel(self.gbox_meas_set_params)
        self.lbl_signal_type.setObjectName("lbl_signal_type")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_signal_type)
        self.combo_signal_type = QtWidgets.QComboBox(self.gbox_meas_set_params)
        self.combo_signal_type.setObjectName("combo_signal_type")
        self.formLayout_2.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.combo_signal_type)
        self.lbl_bias_type = QtWidgets.QLabel(self.gbox_meas_set_params)
        self.lbl_bias_type.setObjectName("lbl_bias_type")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_bias_type)
        self.combo_bias_type = QtWidgets.QComboBox(self.gbox_meas_set_params)
        self.combo_bias_type.setObjectName("combo_bias_type")
        self.formLayout_2.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.combo_bias_type)
        self.lbl_notes = QtWidgets.QLabel(self.gbox_meas_set_params)
        self.lbl_notes.setObjectName("lbl_notes")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.lbl_notes)
        self.ln_notes = QtWidgets.QLineEdit(self.gbox_meas_set_params)
        self.ln_notes.setObjectName("ln_notes")
        self.formLayout_2.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.ln_notes)
        self.lbl_save_file = QtWidgets.QLabel(self.gbox_meas_set_params)
        self.lbl_save_file.setObjectName("lbl_save_file")
        self.formLayout_2.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.lbl_save_file)
        self.layout_save_file = QtWidgets.QHBoxLayout()
        self.layout_save_file.setObjectName("layout_save_file")
        self.ln_save_file = QtWidgets.QLineEdit(self.gbox_meas_set_params)
        self.ln_save_file.setObjectName("ln_save_file")
        self.layout_save_file.addWidget(self.ln_save_file)
        self.btn_save_file = QtWidgets.QToolButton(self.gbox_meas_set_params)
        self.btn_save_file.setObjectName("btn_save_file")
        self.layout_save_file.addWidget(self.btn_save_file)
        self.formLayout_2.setLayout(9, QtWidgets.QFormLayout.FieldRole, self.layout_save_file)
        self.horizontalLayout.addWidget(self.gbox_meas_set_params)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.formLayout_5 = QtWidgets.QFormLayout()
        self.formLayout_5.setObjectName("formLayout_5")
        self.lbl_temp_control = QtWidgets.QLabel(self.tab_meas_setup)
        self.lbl_temp_control.setObjectName("lbl_temp_control")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_temp_control)
        self.combo_temp_control = QtWidgets.QComboBox(self.tab_meas_setup)
        self.combo_temp_control.setObjectName("combo_temp_control")
        self.formLayout_5.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.combo_temp_control)
        self.verticalLayout_9.addLayout(self.formLayout_5)
        self.line = QtWidgets.QFrame(self.tab_meas_setup)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_9.addWidget(self.line)
        self.gbox_thermal_settings = QtWidgets.QGroupBox(self.tab_meas_setup)
        self.gbox_thermal_settings.setObjectName("gbox_thermal_settings")
        self.formLayout_3 = QtWidgets.QFormLayout(self.gbox_thermal_settings)
        self.formLayout_3.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout_3.setObjectName("formLayout_3")
        self.lbl_ramp = QtWidgets.QLabel(self.gbox_thermal_settings)
        self.lbl_ramp.setObjectName("lbl_ramp")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_ramp)
        self.ln_ramp = QtWidgets.QLineEdit(self.gbox_thermal_settings)
        self.ln_ramp.setObjectName("ln_ramp")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ln_ramp)
        self.lbl_dwell = QtWidgets.QLabel(self.gbox_thermal_settings)
        self.lbl_dwell.setObjectName("lbl_dwell")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.lbl_dwell)
        self.ln_dwell = QtWidgets.QLineEdit(self.gbox_thermal_settings)
        self.ln_dwell.setObjectName("ln_dwell")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ln_dwell)
        self.lbl_stability_interval = QtWidgets.QLabel(self.gbox_thermal_settings)
        self.lbl_stability_interval.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_stability_interval.setObjectName("lbl_stability_interval")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.lbl_stability_interval)
        self.ln_stab_int = QtWidgets.QLineEdit(self.gbox_thermal_settings)
        self.ln_stab_int.setObjectName("ln_stab_int")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.ln_stab_int)
        self.lbl_temp_tol = QtWidgets.QLabel(self.gbox_thermal_settings)
        self.lbl_temp_tol.setObjectName("lbl_temp_tol")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.lbl_temp_tol)
        self.ln_temp_tol = QtWidgets.QLineEdit(self.gbox_thermal_settings)
        self.ln_temp_tol.setObjectName("ln_temp_tol")
        self.formLayout_3.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.ln_temp_tol)
        self.lbl_stdev_tol = QtWidgets.QLabel(self.gbox_thermal_settings)
        self.lbl_stdev_tol.setObjectName("lbl_stdev_tol")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.lbl_stdev_tol)
        self.ln_stdev_tol = QtWidgets.QLineEdit(self.gbox_thermal_settings)
        self.ln_stdev_tol.setObjectName("ln_stdev_tol")
        self.formLayout_3.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.ln_stdev_tol)
        self.lbl_z_stability = QtWidgets.QLabel(self.gbox_thermal_settings)
        self.lbl_z_stability.setObjectName("lbl_z_stability")
        self.formLayout_3.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.lbl_z_stability)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.check_z_stability = QtWidgets.QCheckBox(self.gbox_thermal_settings)
        self.check_z_stability.setText("")
        self.check_z_stability.setObjectName("check_z_stability")
        self.horizontalLayout_9.addWidget(self.check_z_stability)
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout_4.setObjectName("formLayout_4")
        self.lbl_z_stdev_tol = QtWidgets.QLabel(self.gbox_thermal_settings)
        self.lbl_z_stdev_tol.setObjectName("lbl_z_stdev_tol")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_z_stdev_tol)
        self.ln_z_stdev_tol = QtWidgets.QLineEdit(self.gbox_thermal_settings)
        self.ln_z_stdev_tol.setObjectName("ln_z_stdev_tol")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.ln_z_stdev_tol)
        self.horizontalLayout_9.addLayout(self.formLayout_4)
        self.horizontalLayout_9.setStretch(1, 1)
        self.formLayout_3.setLayout(5, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_9)
        self.lbl_return_to_rt = QtWidgets.QLabel(self.gbox_thermal_settings)
        self.lbl_return_to_rt.setObjectName("lbl_return_to_rt")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.lbl_return_to_rt)
        self.check_return_to_rt = QtWidgets.QCheckBox(self.gbox_thermal_settings)
        self.check_return_to_rt.setText("")
        self.check_return_to_rt.setChecked(True)
        self.check_return_to_rt.setObjectName("check_return_to_rt")
        self.formLayout_3.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.check_return_to_rt)
        self.lbl_always_stab = QtWidgets.QLabel(self.gbox_thermal_settings)
        self.lbl_always_stab.setObjectName("lbl_always_stab")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.lbl_always_stab)
        self.check_always_stab = QtWidgets.QCheckBox(self.gbox_thermal_settings)
        self.check_always_stab.setChecked(True)
        self.check_always_stab.setObjectName("check_always_stab")
        self.formLayout_3.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.check_always_stab)
        self.verticalLayout_9.addWidget(self.gbox_thermal_settings)
        self.verticalLayout_9.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.gbox_meas_setup = QtWidgets.QGroupBox(self.tab_meas_setup)
        self.gbox_meas_setup.setObjectName("gbox_meas_setup")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbox_meas_setup)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.lbl_num_meas = QtWidgets.QLabel(self.gbox_meas_setup)
        self.lbl_num_meas.setObjectName("lbl_num_meas")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.lbl_num_meas)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ln_num_meas = QtWidgets.QLineEdit(self.gbox_meas_setup)
        self.ln_num_meas.setObjectName("ln_num_meas")
        self.horizontalLayout_11.addWidget(self.ln_num_meas)
        self.btn_copy_table = QtWidgets.QPushButton(self.gbox_meas_setup)
        self.btn_copy_table.setObjectName("btn_copy_table")
        self.horizontalLayout_11.addWidget(self.btn_copy_table)
        self.btn_paste_table = QtWidgets.QPushButton(self.gbox_meas_setup)
        self.btn_paste_table.setObjectName("btn_paste_table")
        self.horizontalLayout_11.addWidget(self.btn_paste_table)
        self.formLayout.setLayout(0, QtWidgets.QFormLayout.FieldRole, self.horizontalLayout_11)
        self.verticalLayout.addLayout(self.formLayout)
        self.table_meas_setup = QtWidgets.QTableWidget(self.gbox_meas_setup)
        self.table_meas_setup.setObjectName("table_meas_setup")
        self.table_meas_setup.setColumnCount(0)
        self.table_meas_setup.setRowCount(0)
        self.verticalLayout.addWidget(self.table_meas_setup)
        self.verticalLayout_2.addWidget(self.gbox_meas_setup)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btn_setup_start_stop = QtWidgets.QPushButton(self.tab_meas_setup)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_setup_start_stop.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/run.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap(":/img/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.btn_setup_start_stop.setIcon(icon)
        self.btn_setup_start_stop.setIconSize(QtCore.QSize(50, 50))
        self.btn_setup_start_stop.setCheckable(True)
        self.btn_setup_start_stop.setChecked(False)
        self.btn_setup_start_stop.setObjectName("btn_setup_start_stop")
        self.horizontalLayout_4.addWidget(self.btn_setup_start_stop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.horizontalLayout_4.setStretch(0, 1)
        self.horizontalLayout_4.setStretch(1, 2)
        self.horizontalLayout_4.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        cap_freq.addTab(self.tab_meas_setup, "")
        self.tab_run_meas = QtWidgets.QWidget()
        self.tab_run_meas.setObjectName("tab_run_meas")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_run_meas)
        self.verticalLayout_5.setContentsMargins(30, 30, 30, 30)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.vlayout_current_vals = QtWidgets.QVBoxLayout()
        self.vlayout_current_vals.setObjectName("vlayout_current_vals")
        self.gbox_curr_freq = QtWidgets.QGroupBox(self.tab_run_meas)
        self.gbox_curr_freq.setObjectName("gbox_curr_freq")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.gbox_curr_freq)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.lbl_curr_freq = QtWidgets.QLabel(self.gbox_curr_freq)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_curr_freq.sizePolicy().hasHeightForWidth())
        self.lbl_curr_freq.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_curr_freq.setFont(font)
        self.lbl_curr_freq.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_curr_freq.setLineWidth(3)
        self.lbl_curr_freq.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_curr_freq.setObjectName("lbl_curr_freq")
        self.horizontalLayout_7.addWidget(self.lbl_curr_freq)
        self.vlayout_current_vals.addWidget(self.gbox_curr_freq)
        self.gbox_curr_temp = QtWidgets.QGroupBox(self.tab_run_meas)
        self.gbox_curr_temp.setObjectName("gbox_curr_temp")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.gbox_curr_temp)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lbl_curr_temp = QtWidgets.QLabel(self.gbox_curr_temp)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_curr_temp.setFont(font)
        self.lbl_curr_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_curr_temp.setObjectName("lbl_curr_temp")
        self.verticalLayout_6.addWidget(self.lbl_curr_temp)
        self.hlayout_temp_channel = QtWidgets.QWidget(self.gbox_curr_temp)
        self.hlayout_temp_channel.setObjectName("hlayout_temp_channel")
        self.hlayout = QtWidgets.QHBoxLayout(self.hlayout_temp_channel)
        self.hlayout.setObjectName("hlayout")
        self.radio_chamber_tc = QtWidgets.QRadioButton(self.hlayout_temp_channel)
        self.radio_chamber_tc.setChecked(True)
        self.radio_chamber_tc.setObjectName("radio_chamber_tc")
        self.hlayout.addWidget(self.radio_chamber_tc)
        self.radio_user_tc = QtWidgets.QRadioButton(self.hlayout_temp_channel)
        self.radio_user_tc.setChecked(False)
        self.radio_user_tc.setObjectName("radio_user_tc")
        self.hlayout.addWidget(self.radio_user_tc)
        self.verticalLayout_6.addWidget(self.hlayout_temp_channel)
        self.vlayout_current_vals.addWidget(self.gbox_curr_temp)
        self.gbox_val1 = QtWidgets.QGroupBox(self.tab_run_meas)
        self.gbox_val1.setObjectName("gbox_val1")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.gbox_val1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.lbl_val1 = QtWidgets.QLabel(self.gbox_val1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_val1.sizePolicy().hasHeightForWidth())
        self.lbl_val1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_val1.setFont(font)
        self.lbl_val1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_val1.setLineWidth(3)
        self.lbl_val1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_val1.setObjectName("lbl_val1")
        self.horizontalLayout_6.addWidget(self.lbl_val1)
        self.vlayout_current_vals.addWidget(self.gbox_val1)
        self.gbox_val2 = QtWidgets.QGroupBox(self.tab_run_meas)
        self.gbox_val2.setObjectName("gbox_val2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gbox_val2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lbl_val2 = QtWidgets.QLabel(self.gbox_val2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_val2.sizePolicy().hasHeightForWidth())
        self.lbl_val2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_val2.setFont(font)
        self.lbl_val2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.lbl_val2.setLineWidth(3)
        self.lbl_val2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_val2.setObjectName("lbl_val2")
        self.horizontalLayout_3.addWidget(self.lbl_val2)
        self.vlayout_current_vals.addWidget(self.gbox_val2)
        self.btn_run_start_stop = QtWidgets.QPushButton(self.tab_run_meas)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_run_start_stop.setFont(font)
        self.btn_run_start_stop.setIcon(icon)
        self.btn_run_start_stop.setIconSize(QtCore.QSize(50, 50))
        self.btn_run_start_stop.setCheckable(True)
        self.btn_run_start_stop.setObjectName("btn_run_start_stop")
        self.vlayout_current_vals.addWidget(self.btn_run_start_stop)
        self.vlayout_current_vals.setStretch(0, 5)
        self.vlayout_current_vals.setStretch(1, 5)
        self.vlayout_current_vals.setStretch(2, 5)
        self.vlayout_current_vals.setStretch(3, 5)
        self.vlayout_current_vals.setStretch(4, 1)
        self.horizontalLayout_8.addLayout(self.vlayout_current_vals)
        self.live_plot = LivePlotWidget(self.tab_run_meas)
        self.live_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.live_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.live_plot.setObjectName("live_plot")
        self.horizontalLayout_8.addWidget(self.live_plot)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 5)
        self.verticalLayout_5.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.tab_run_meas)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_start = QtWidgets.QLabel(self.groupBox)
        self.lbl_start.setObjectName("lbl_start")
        self.horizontalLayout_2.addWidget(self.lbl_start)
        self.lbl_curr_meas_start = QtWidgets.QLabel(self.groupBox)
        self.lbl_curr_meas_start.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_curr_meas_start.setObjectName("lbl_curr_meas_start")
        self.horizontalLayout_2.addWidget(self.lbl_curr_meas_start)
        self.lbl_pipe1 = QtWidgets.QLabel(self.groupBox)
        self.lbl_pipe1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pipe1.setObjectName("lbl_pipe1")
        self.horizontalLayout_2.addWidget(self.lbl_pipe1)
        self.lbl_stop = QtWidgets.QLabel(self.groupBox)
        self.lbl_stop.setObjectName("lbl_stop")
        self.horizontalLayout_2.addWidget(self.lbl_stop)
        self.lbl_curr_meas_stop = QtWidgets.QLabel(self.groupBox)
        self.lbl_curr_meas_stop.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_curr_meas_stop.setObjectName("lbl_curr_meas_stop")
        self.horizontalLayout_2.addWidget(self.lbl_curr_meas_stop)
        self.lbl_pipe2 = QtWidgets.QLabel(self.groupBox)
        self.lbl_pipe2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pipe2.setObjectName("lbl_pipe2")
        self.horizontalLayout_2.addWidget(self.lbl_pipe2)
        self.lbl_osc = QtWidgets.QLabel(self.groupBox)
        self.lbl_osc.setObjectName("lbl_osc")
        self.horizontalLayout_2.addWidget(self.lbl_osc)
        self.lbl_curr_meas_osc = QtWidgets.QLabel(self.groupBox)
        self.lbl_curr_meas_osc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_curr_meas_osc.setObjectName("lbl_curr_meas_osc")
        self.horizontalLayout_2.addWidget(self.lbl_curr_meas_osc)
        self.lbl_pipe3 = QtWidgets.QLabel(self.groupBox)
        self.lbl_pipe3.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pipe3.setObjectName("lbl_pipe3")
        self.horizontalLayout_2.addWidget(self.lbl_pipe3)
        self.lbl_bias = QtWidgets.QLabel(self.groupBox)
        self.lbl_bias.setObjectName("lbl_bias")
        self.horizontalLayout_2.addWidget(self.lbl_bias)
        self.lbl_curr_meas_bias = QtWidgets.QLabel(self.groupBox)
        self.lbl_curr_meas_bias.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_curr_meas_bias.setObjectName("lbl_curr_meas_bias")
        self.horizontalLayout_2.addWidget(self.lbl_curr_meas_bias)
        self.lbl_pipe4 = QtWidgets.QLabel(self.groupBox)
        self.lbl_pipe4.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_pipe4.setObjectName("lbl_pipe4")
        self.horizontalLayout_2.addWidget(self.lbl_pipe4)
        self.lbl_temp = QtWidgets.QLabel(self.groupBox)
        self.lbl_temp.setObjectName("lbl_temp")
        self.horizontalLayout_2.addWidget(self.lbl_temp)
        self.lbl_curr_meas_temp = QtWidgets.QLabel(self.groupBox)
        self.lbl_curr_meas_temp.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lbl_curr_meas_temp.setObjectName("lbl_curr_meas_temp")
        self.horizontalLayout_2.addWidget(self.lbl_curr_meas_temp)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.progress_bar_meas = QtWidgets.QProgressBar(self.tab_run_meas)
        self.progress_bar_meas.setProperty("value", 0)
        self.progress_bar_meas.setObjectName("progress_bar_meas")
        self.verticalLayout_4.addWidget(self.progress_bar_meas)
        self.horizontalLayout_5.addLayout(self.verticalLayout_4)
        self.lbl_meas_progress = QtWidgets.QLabel(self.tab_run_meas)
        self.lbl_meas_progress.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_meas_progress.setObjectName("lbl_meas_progress")
        self.horizontalLayout_5.addWidget(self.lbl_meas_progress)
        self.horizontalLayout_5.setStretch(0, 7)
        self.horizontalLayout_5.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        self.lbl_meas_status = QtWidgets.QLabel(self.tab_run_meas)
        self.lbl_meas_status.setText("")
        self.lbl_meas_status.setObjectName("lbl_meas_status")
        self.verticalLayout_5.addWidget(self.lbl_meas_status)
        cap_freq.addTab(self.tab_run_meas, "")

        self.retranslateUi(cap_freq)
        cap_freq.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(cap_freq)

    def retranslateUi(self, cap_freq):
        _translate = QtCore.QCoreApplication.translate
        cap_freq.setWindowTitle(_translate("cap_freq", "TabWidget"))
        self.gbox_meas_set_params.setTitle(_translate("cap_freq", "Measurement Set Parameters:"))
        self.lbl_function.setText(_translate("cap_freq", "LCR Function:"))
        self.lbl_meas_time.setText(_translate("cap_freq", "Measuring Time:"))
        self.lbl_data_averaging.setText(_translate("cap_freq", "Data Averaging:"))
        self.lbl_num_pts.setText(_translate("cap_freq", "# of Data Points:"))
        self.lbl_pre_meas_delay.setText(_translate("cap_freq", "Measurement Delay:"))
        self.lbl_range.setText(_translate("cap_freq", "Impedance Range:"))
        self.lbl_signal_type.setText(_translate("cap_freq", "Signal Type:"))
        self.lbl_bias_type.setText(_translate("cap_freq", "DC Bias Type:"))
        self.lbl_notes.setText(_translate("cap_freq", "Sample Memo:"))
        self.lbl_save_file.setText(_translate("cap_freq", "Save Location:"))
        self.btn_save_file.setText(_translate("cap_freq", "..."))
        self.lbl_temp_control.setText(_translate("cap_freq", "Temperature Control Device:"))
        self.gbox_thermal_settings.setTitle(_translate("cap_freq", "Thermal Management Settings"))
        self.lbl_ramp.setText(_translate("cap_freq", "Ramp Rate:"))
        self.lbl_dwell.setText(_translate("cap_freq", "Equilibration Time:"))
        self.lbl_stability_interval.setToolTip(_translate("cap_freq", "<html><head/><body><p>Sets the interval (in s) between measurements during the temperature stability check.</p></body></html>"))
        self.lbl_stability_interval.setText(_translate("cap_freq", "Meas Interval:"))
        self.lbl_temp_tol.setText(_translate("cap_freq", "Temp Tolerance:"))
        self.lbl_stdev_tol.setText(_translate("cap_freq", "Variation Tolerance:"))
        self.lbl_z_stability.setText(_translate("cap_freq", "Verify Impedance\n"
"Stability:"))
        self.lbl_z_stdev_tol.setText(_translate("cap_freq", "Z Variation Tolerance:"))
        self.lbl_return_to_rt.setText(_translate("cap_freq", "Return to RT?"))
        self.lbl_always_stab.setToolTip(_translate("cap_freq", "<html><head/><body><p>Check this box if you want to stabilize temperature between measurements with the same temperature setpoint.</p></body></html>"))
        self.lbl_always_stab.setText(_translate("cap_freq", "Always Stabilize?"))
        self.check_always_stab.setToolTip(_translate("cap_freq", "<html><head/><body><p>Check this box if you want to stabilize temperature between measurements with the same temperature setpoint.</p></body></html>"))
        self.gbox_meas_setup.setTitle(_translate("cap_freq", "Measurement(s) Setup:"))
        self.lbl_num_meas.setText(_translate("cap_freq", "Number of Measurements: "))
        self.btn_copy_table.setText(_translate("cap_freq", "Copy Measurement Table"))
        self.btn_paste_table.setText(_translate("cap_freq", "Paste Measurement From Excel"))
        self.btn_setup_start_stop.setText(_translate("cap_freq", "Run Measurement Set"))
        cap_freq.setTabText(cap_freq.indexOf(self.tab_meas_setup), _translate("cap_freq", "Measurement Setup"))
        self.gbox_curr_freq.setTitle(_translate("cap_freq", "Current Frequency:"))
        self.lbl_curr_freq.setText(_translate("cap_freq", "999.99 MHz"))
        self.gbox_curr_temp.setTitle(_translate("cap_freq", "Current Temperature:"))
        self.lbl_curr_temp.setText(_translate("cap_freq", "XX.XX C"))
        self.radio_chamber_tc.setText(_translate("cap_freq", "ChamberTC"))
        self.radio_user_tc.setText(_translate("cap_freq", "User TC"))
        self.gbox_val1.setTitle(_translate("cap_freq", "Val1:"))
        self.lbl_val1.setText(_translate("cap_freq", "12345.12"))
        self.gbox_val2.setTitle(_translate("cap_freq", "Val2:"))
        self.lbl_val2.setText(_translate("cap_freq", "Value 2"))
        self.btn_run_start_stop.setText(_translate("cap_freq", "Run Measurement Set"))
        self.groupBox.setTitle(_translate("cap_freq", "Current Measurement Parameters:"))
        self.lbl_start.setText(_translate("cap_freq", "Start:"))
        self.lbl_curr_meas_start.setText(_translate("cap_freq", "- - - -"))
        self.lbl_pipe1.setText(_translate("cap_freq", "  |  "))
        self.lbl_stop.setText(_translate("cap_freq", "Stop:"))
        self.lbl_curr_meas_stop.setText(_translate("cap_freq", "- - - -"))
        self.lbl_pipe2.setText(_translate("cap_freq", "  |  "))
        self.lbl_osc.setText(_translate("cap_freq", "Oscillator:"))
        self.lbl_curr_meas_osc.setText(_translate("cap_freq", "- - - -"))
        self.lbl_pipe3.setText(_translate("cap_freq", "  |  "))
        self.lbl_bias.setText(_translate("cap_freq", "Bias:"))
        self.lbl_curr_meas_bias.setText(_translate("cap_freq", "- - - -"))
        self.lbl_pipe4.setText(_translate("cap_freq", "  |  "))
        self.lbl_temp.setText(_translate("cap_freq", "Temperature:"))
        self.lbl_curr_meas_temp.setText(_translate("cap_freq", "- - - - "))
        self.lbl_meas_progress.setText(_translate("cap_freq", "\'Measurement 0/0,\n"
"Step 0/0\'"))
        cap_freq.setTabText(cap_freq.indexOf(self.tab_run_meas), _translate("cap_freq", "Run Mreasurement"))

from Live_Data_Plotter import LivePlotWidget
from src.ui import resources_rc
